# Generated by Django 5.0 on 2023-12-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_main_catagory_catagory_sub_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Main_Catagory',
            new_name='Main_Category',
        ),
        migrations.RenameModel(
            old_name='Sub_Catagory',
            new_name='Sub_Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='main_catagory',
            new_name='main_category',
        ),
        migrations.RenameField(
            model_name='sub_category',
            old_name='catagory',
            new_name='category',
        ),
    ]
