# Generated by Django 5.0 on 2023-12-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_catagory_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catagory',
        ),
        migrations.RenameModel(
            old_name='Main_Category',
            new_name='Main_Catagory',
        ),
        migrations.RenameModel(
            old_name='Sub_Category',
            new_name='Sub_Catagory',
        ),
        migrations.RenameField(
            model_name='catagory',
            old_name='main_category',
            new_name='main_catagory',
        ),
        migrations.RenameField(
            model_name='sub_catagory',
            old_name='category',
            new_name='catagory',
        ),
    ]
