# Generated by Django 5.0 on 2023-12-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additional_information',
            old_name='details',
            new_name='detail',
        ),
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
