# Generated by Django 5.0 on 2023-12-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_details_additional_information_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(),
        ),
    ]
