# Generated by Django 5.0 on 2024-01-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='name',
        ),
    ]
