# Generated by Django 5.0 on 2024-01-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
