# Generated by Django 5.0 on 2024-01-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_order_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='use',
            new_name='user',
        ),
    ]
