# Generated by Django 5.0 on 2024-01-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_use_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
