# Generated by Django 5.0 on 2024-01-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_order_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delevered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
