# Generated by Django 5.0 on 2024-01-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_order_is_delevered_order_is_dispatched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_delevered',
            new_name='delevered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_dispatched',
            new_name='dispatched',
        ),
        migrations.AddField(
            model_name='order',
            name='packaging',
            field=models.BooleanField(default=False),
        ),
    ]
