# Generated by Django 5.0 on 2024-01-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delevered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dispatched',
        ),
        migrations.RemoveField(
            model_name='order',
            name='packaging',
        ),
    ]
