# Generated by Django 5.0 on 2024-01-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_order_created_at_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delevered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='packaged',
            field=models.BooleanField(default=False),
        ),
    ]
