# Generated by Django 5.0 on 2024-01-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_order_delevered_order_dispatched_order_packaged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delevered',
            new_name='delivered',
        ),
    ]
