# Generated by Django 5.0 on 2024-01-04 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_section_timer_ends_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='timer_ends_at',
        ),
    ]
