# Generated by Django 5.0 on 2024-01-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_section_timer_ends_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationPannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offerprice', models.IntegerField()),
                ('product_value', models.IntegerField()),
            ],
        ),
    ]
