# Generated by Django 5.0 on 2024-01-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_negotiationpannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationpannel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
